spring:
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/wb
    username: root
    password: 123456

jwt:
  secret: qwehjkijnqwehjkijnjkijnqwehjkijnqwehjkijnqwehjkijnjkijnqwehjkijnqwehjkijnqwehjkijnjkijnqwehjkijnqwehjkijnqwehjkijnjkijnqwehjkijn
  expireTime: 7200